### ISSUE TITLE
Switch to a more advanced pretty printing library

### ISSUE THREAD

**Issue by mmhat** [knrafto/language-bash#28]
It would be nice if we support `Text` pretty printing in addition to simple `String`s.
We could use grouping features to improve the output as well.
Personal choice: [prettyprinter](https://hackage.haskell.org/package/prettyprinter)

**Comment by mmhat** [comment]
Draft i [here](https://github.com/mmhat/language-bash/tree/prettyprinter). Passes all tests in #30.
But I don't want to make a pull request before discussing this issue.

**Comment by knrafto** [comment]
I'm all for it, prettyprinter seems to be the best choice nowadays.

**Comment by knrafto** [comment]
I should add that the only reason this library doesn't use `prettyprinter` is that `prettyprinter` didn't exist when this project started. We should upgrade the other dependencies too (e.g. Parsec -> Megaparsec #31)
