### ISSUE TITLE
Rename ppCond ppCondList

### ISSUE THREAD

**Issue by knrafto** [knrafto/language-bash#35]
Minor leftover point from #33.

IMO I don't think "conditional command" is accurate, maybe "block command" would be better terminology.

**Comment by mmhat** [comment]
Like `ppBlock` and `ppBlockList` ?

**Comment by knrafto** [comment]
Yeah, or maybe `prettyBlock` (since `pretty` is more common than `pp` as a prefix in that file)

**Comment by mmhat** [comment]
Ok, let's go with that.

**Comment by knrafto** [comment]
Fixed by #36
